// <auto-generated />
using System;
using LibraryBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryBackend.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260315170835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryBackend.Models.AdminNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LoanId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("LoanId");

                    b.HasIndex("UserId");

                    b.ToTable("AdminNotes");
                });

            modelBuilder.Entity("LibraryBackend.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jane Writer",
                            AvailableCopies = 4,
                            CoverUrl = "",
                            CreatedAt = new DateTime(2026, 3, 15, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Description = "A heartwarming story about a small-town library.",
                            Genre = "fiction",
                            Title = "The Cozy Library",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 2,
                            Author = "ML Expert",
                            AvailableCopies = 2,
                            CoverUrl = "",
                            CreatedAt = new DateTime(2026, 3, 15, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Description = "Practical guide to ML.NET and production ML.",
                            Genre = "technology",
                            Title = "Deep Learning with .NET",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 3,
                            Author = "Story Teller",
                            AvailableCopies = 4,
                            CoverUrl = "",
                            CreatedAt = new DateTime(2026, 3, 15, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Description = "Short fantasy stories for all ages.",
                            Genre = "fantasy",
                            Title = "Fantasy Tales",
                            TotalCopies = 4
                        });
                });

            modelBuilder.Entity("LibraryBackend.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowedAt = new DateTime(2026, 3, 5, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            DueDate = new DateTime(2026, 3, 13, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Status = "active",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowedAt = new DateTime(2026, 2, 23, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            DueDate = new DateTime(2026, 3, 10, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            ReturnedAt = new DateTime(2026, 3, 12, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Status = "returned",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LibraryBackend.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PickupDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            QueuePosition = 1,
                            RequestedAt = new DateTime(2026, 3, 14, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Status = "queued",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LibraryBackend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 2,
                            Comment = "Great intro to ML.NET and production ML!",
                            CreatedAt = new DateTime(2026, 3, 8, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Rating = 5,
                            Sentiment = "positive",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LibraryBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 15, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Email = "admin@library.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$fVCmDg8kz/aU4ZAB2TtpY.YYvICWTTI/9dGT2yTsaikT.A1NE5zUO",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 15, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Email = "alice@example.com",
                            Name = "Alice",
                            PasswordHash = "$2a$11$EvJkHjU6EumXXebcMmth1u4S8Xo3YuEE5L4SJSHrw1WGKcFpTCpwq",
                            Role = "user"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 15, 17, 8, 34, 53, DateTimeKind.Utc).AddTicks(9381),
                            Email = "bob@example.com",
                            Name = "Bob",
                            PasswordHash = "$2a$11$oOLzi4tBWO1yX1b5K.rC4uzhIO7E.B5yRs8pr8z0EZfJ.STRUq31q",
                            Role = "user"
                        });
                });

            modelBuilder.Entity("LibraryBackend.Models.AdminNote", b =>
                {
                    b.HasOne("LibraryBackend.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBackend.Models.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId");

                    b.HasOne("LibraryBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Loan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryBackend.Models.Loan", b =>
                {
                    b.HasOne("LibraryBackend.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBackend.Models.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryBackend.Models.Reservation", b =>
                {
                    b.HasOne("LibraryBackend.Models.Book", "Book")
                        .WithMany("Reservations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBackend.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryBackend.Models.Review", b =>
                {
                    b.HasOne("LibraryBackend.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBackend.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryBackend.Models.Book", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LibraryBackend.Models.User", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
